# Generated by Django 5.1.3 on 2024-11-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_remove_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('функциональный блок', 'Функциональный блок'), ('подразделение', 'Подразделение')], max_length=50),
        ),
    ]
