services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mts-backend:
    build: ./backend
    container_name: mts-backend
    command: bash -c "
      python mts_hahaton/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  mts-frontend:
    build: ./frontend
    container_name: mts-frontend
    ports:
      - "4000:4000"

volumes:
  postgres_data:
