FROM python:3.12

WORKDIR app/
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Команда для запуска
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "mts_hahaton.wsgi:application"]